In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [ ]:
class Classification:
    def __init__(self, data):
        self.data = data
        self.p, self.N = self.data.shape
        self.X = self.data[0:self.p-1,:]
        self.Y = self.data[self.p-1,:]
        
    def show_graph(self):
        pass

In [18]:
data = np.loadtxt('EMGsDataset.csv', delimiter=',')
c = Classification(data)
print(c.data.shape)
print(c.p)
print(c.N)
print(c.X)
print(c.Y)

(3, 50000)
3
50000
[[   0.    0.  905. ...    0.    0.    0.]
 [   0.    0. 1430. ...    0. 3941. 3938.]]
[1. 1. 4. ... 1. 2. 2.]
